### ISSUE TITLE
[E] 0x108600fd0 socks5 client AND. 0x108600fd0 socks5 session connect

### ISSUE THREAD

**Issue by hassanAzhar143** [EbrahimTahernejad/Tun2SocksKit#11]
I am having this issue using 
MANGO version 2.3.0
keep printing these lines

**Comment by hassanAzhar143** [comment]
private func startSocks5Tunnel(serverPort port: Int) throws {
        let config = """
        tunnel:
          mtu: 9000
        socks5:
          port: \(port)
          address: ::1
          udp: 'udp'
        misc:
          task-stack-size: 2048
          connect-timeout: 5000
          read-write-timeout: 60000
          log-file: stderr
          log-level: error
          limit-nofile: 65535
        """
        let configurationFilePath = MGConstant.cachesDirectory.appending(component: "config.yml").path(percentEncoded: false)
        guard FileManager.default.createFile(atPath: configurationFilePath, contents: config.data(using: .utf8)!) else {
            throw NSError.newError("Tunnel 配置文件写入失败")
        }
        DispatchQueue.global(qos: .userInitiated).async {
            NSLog("HEV_SOCKS5_TUNNEL_MAIN: \(Socks5Tunnel.run(withConfig: .file(path: URL.init(string:configurationFilePath)!)))")
        }
    }

**Comment by hassanAzhar143** [comment]
here default port is 8080

**Comment by EbrahimTahernejad** [comment]
Use version 3.6.8

**Comment by EbrahimTahernejad** [comment]
(port)
->
\(port)

**Comment by hassanAzhar143** [comment]
I used it after updating version i have failed proxy issue,VMESS proxy SOCKS 5 for inbound,port is from xray, on which i started tunnel and Xray for same inbound,,am I correct?

**Comment by hassanAzhar143** [comment]
THIS IS SERVER ERROR,,,,
app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [context canceled dial tcp: lookup DOMAIN: operation was canceled] > common/retry: all retry attempts failed
THIS IS CLIENT ERROR....
2024/05/17 05:07:41 [Warning] [2708033371] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [context canceled dial tcp: lookup DOMAIN operation was canceled] > common/retry: all retry attempts failed
[2024-05-17 10:07:48] [E] 0x103dddb30 socks5 client read auth
[2024-05-17 10:07:48] [E] 0x103dddb30 socks5 session handshake
[2024-05-17 10:07:48] [E] 0x103dde770 socks5 client read auth
[2024-05-17 10:07:48] [E] 0x103dde770 socks5 session handshake
,I am facing now

**Comment by hassanAzhar143** [comment]
2024/05/17 04:52:32 [Warning] [1271992904] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp …:8080: i/o timeout dial tcp: lookup japan-proxy.b-cube.tech: operation was canceled] > common/retry: all retry attempts failed

THIS THE ERROR I AM FACING NOW,,

**Comment by hassanAzhar143** [comment]
Could you guide me with any sample code for that.

**Comment by hassanAzhar143** [comment]
how to send TCP traffic from tunnel?
how it support multiple ports for inbound?

**Comment by hassanAzhar143** [comment]
Hi there, any suggestions how to read and write data to tunnel and,
TCP message by server is not handled , how to make tcp connection,?

**Comment by EbrahimTahernejad** [comment]
As you can read in the logs, this is an issue with your proxy library
configuration, not an issue with tun2socks.
Please check your configuration.
