### ISSUE TITLE
Code compilation error

### ISSUE THREAD

**Issue by dhp5** [EbrahimTahernejad/Tun2SocksKit#20]
Hello.I encountered a bug while using this code
My Xcode version:v14.3.1
Tun2socksKit version : 4.7.5

    public static func run(withConfig config: Config) -> Int32 {
        guard let fileDescriptor = tunnelFileDescriptor else {
            return -1
        }
        switch config {
        case .file(let path):
            return hev_socks5_tunnel_main(path.path.cString(using: .utf8), fileDescriptor)
        case .string(let content):
            return hev_socks5_tunnel_main_from_str(content.cString(using: .utf8), UInt32(content.count), fileDescriptor)
        }
    }
The error message is : Cannot convert value of type '[CChar]?' (aka 'Optional<Array<Int8>>') to expected argument type 'UnsafePointer<UInt8>?'

May I ask how I should proceed?

**Comment by EbrahimTahernejad** [comment]
I have no idea to be honest,
I know it works with the latest Xcode 15 and 16.
