### ISSUE TITLE
Thanks for the amazing work. But I'm new to iOS development, how to input ip packets into tun2socks sever?

### ISSUE THREAD

**Issue by AndyLeeNH** [EbrahimTahernejad/Tun2SocksKit#3]
solved

**Comment by AndyLeeNH** [comment]
And how can i read responds from tun2socks?

**Comment by AndyLeeNH** [comment]
> And how can i read responds from tun2socks?

through Socks5Tunnel.tunnelFileDescriptor and work with NSFileHandle?
but it's a private var of Socks5Tunnel
<img width="913" alt="image" src="https://github.com/EbrahimTahernejad/Tun2SocksKit/assets/31917826/d8cc0d40-566e-4204-a4af-ad5d504e5dd2">

**Comment by AndyLeeNH** [comment]
solved

**Comment by dhp5** [comment]
Hello，Could you please tell me how you did it?
